  AWSTemplateFormatVersion: "2010-09-09"
  Description:
  Resources:
    DummyServer:
      Type: "AWS::EC2::Instance"
      Properties:
        ImageId: ""
    DB:
      Type: "AWS::RDS::DBCluster"
      Properties:
        Engine: "aurora"
        DBClusterIdentifier: "merchant-db"
