version: '3.9'

services:
  catalog:
    restart: always
    image: 106647883331.dkr.ecr.ca-central-1.amazonaws.com/merchant/catalog
    deploy:
      x-aws-autoscaling:
        min: 1
        max: 10 #required
        cpu: 75
    ports:
      - "80:80"
    environment:
      HOST: '0.tcp.ngrok.io'
      PORT: '15009'
      USER: 'user'
      PASSWORD: 'password'
      DB: 'MERCHANT'
      EXPRESS_PORT: '80'
      CORS_ORIGIN: 'http://127.0.0.1:8080'
    logging:
      driver: awslogs
