version: '3.9'

services:
  catalog:
    restart: always
    image: merchant/catalog
    pull_policy: never
    deploy:
      x-aws-autoscaling:
        min: 1
        max: 10 #required
        cpu: 75
    expose:
      - 80
    environment:
      HOST: '0.tcp.ngrok.io'
      PORT: '17096'
      USER: 'user'
      PASSWORD: 'password'
      DB: 'MERCHANT'
      EXPRESS_PORT: '80'
      CORS_ORIGIN: 'http://127.0.0.1:3000'
    logging:
      driver: local
  nginx:
    restart: always
    image: merchant/nginx
    pull_policy: never
    deploy:
      x-aws-autoscaling:
        min: 1
        max: 10 #required
        cpu: 75
    ports:
      - "80:80"
    logging:
      driver: local

